SQL_MAIN_QUERY = """
SELECT
    c.PCODE,
    c.LASTNAME,
    c.FIRSTNAME,
    c.MIDNAME,
    COALESCE(
    NULLIF(TRIM(c.ADDRFULL), ''),
    NULLIF(TRIM(c.KLADR_ADDRFULL), ''),
    TRIM(c.CITY) || ', ' || TRIM(c.STREETNAME) || ', д. ' || TRIM(c.ADDR) ||
    COALESCE(', корп. ' || NULLIF(TRIM(c.CORP), ''), '') ||
    COALESCE(', кв. ' || NULLIF(TRIM(c.FLAT), ''), '')
    ) AS FULL_ADDR,
    c.BDATE,
    d_cons.DNAME AS CONSULT_DOCTOR,
    sch.FirstWorkDate,
    d_first.DNAME AS FIRST_DOCTOR,
    CAST(COALESCE(ord.total_sum, 0) AS DOUBLE PRECISION),
    CAST(COALESCE(inc.paid_sum, 0) AS DOUBLE PRECISION),
    c.PHONE1,
    c.PHONE2,
    c.PHONE3,
    c.CLMAIL,
    c.AGESTATUS,
    c.TYPESTATUS,
    cls1.SNAME AS AGESTATUS_NAME,
    cls2.SNAME AS TYPESTATUS_NAME
FROM CLIENTS c
LEFT JOIN DOCTOR d_cons ON d_cons.DCODE = c.DCODE_CONSULT
LEFT JOIN (
    SELECT r.PCODE, r.SCHEDULE_WORKDATE AS FirstWorkDate, r.DCODE
    FROM REP_SCHED_APPEALS_VIEW r
    JOIN (
        SELECT PCODE, MIN(SCHEDULE_WORKDATE) AS MinWorkDate
        FROM REP_SCHED_APPEALS_VIEW
        GROUP BY PCODE
    ) m ON m.PCODE = r.PCODE AND m.MinWorkDate = r.SCHEDULE_WORKDATE
) sch ON sch.PCODE = c.PCODE
LEFT JOIN DOCTOR d_first ON d_first.DCODE = sch.DCODE
LEFT JOIN (
    SELECT PCODE, SUM(SCHPRICE) AS total_sum
    FROM ORDERS
    GROUP BY PCODE
) ord ON ord.PCODE = c.PCODE
LEFT JOIN (
    SELECT PCODE, SUM(OPERAMOUNT) AS paid_sum
    FROM PAYLOG
    GROUP BY PCODE
) inc ON inc.PCODE = c.PCODE
LEFT JOIN CLSTATUS cls1 ON cls1.SID = c.AGESTATUS
LEFT JOIN CLSTATUS cls2 ON cls2.SID = c.TYPESTATUS
WHERE c.PCODE = ?
"""

SQL_GET_LAST_OBSLED = """
SELECT OBSLNUM
FROM OBSLED
WHERE PCODE = ?
ORDER BY OBSLDATE DESC
ROWS 1
"""

SQL_GET_PARAMSINFO = """
SELECT 
    gp.NAMEPARAMS,
    pi.VALUETEXT
FROM PARAMSINFO pi
JOIN GROUPSPARAMS gp ON gp.CODEPARAMS = pi.CODEPARAMS
WHERE pi.TREATCODE = ?
"""

SQL_GET_TREATMENT_PLAN = """
SELECT
    ws.SCHNAME || ' (' || dpd.SCOUNT || ' шт., ' || ROUND(dpd.AMOUNTRUB) || ' руб.)' AS CONCATENATION
FROM DAILYPLAN dp
JOIN DAILYPLANDET dpd ON dp.DID = dpd.DID
JOIN WSCHEMA ws ON dpd.SCHID = ws.SCHID
WHERE dp.PCODE = ?
ORDER BY ws.SCHNAME
"""

SQL_GET_APPOINTMENTS = """
SELECT 
    CAST(r.SCHEDULE_WORKDATE AS VARCHAR(10)) AS work_date_str,
    d.DNAME AS doctor_name,
    f.FULLNAME AS filial_name,
    r.SCHEDAPPEALS_COMMENT
FROM REP_SCHED_APPEALS_VIEW r
LEFT JOIN DOCTOR d ON d.DCODE = r.DCODE
LEFT JOIN FILIALS f ON f.FILID = r.SCHEDFILIAL
WHERE r.PCODE = ? AND r.SCHEDULE_WORKDATE > CURRENT_DATE
ORDER BY r.SCHEDULE_WORKDATE
"""

SQL_GET_COMPLEX_PLANS = """
SELECT 
    dp.DID,
    dp.DEPNUM,
    dpt.DEPNAME,
    dpr.PLANTYPENAME,
    dp.PLANTYPE
FROM DAILYPLAN dp
LEFT JOIN DEPARTMENTS dpt ON dpt.DEPNUM = dp.DEPNUM
JOIN DAILYPLANREF dpr ON dp.PLANTYPE = dpr.PLANTYPE
WHERE dp.PCODE = ?
  AND dp.PLANTYPE IN (1, 2)
ORDER BY dp.DID
"""

SQL_GET_PLAN_DETAILS = """
SELECT 
    ws.SCHNAME,
    dpd.SCOUNT,
    ROUND(dpd.AMOUNTRUB)
FROM DAILYPLANDET dpd
JOIN WSCHEMA ws ON dpd.SCHID = ws.SCHID
WHERE dpd.DID = ?
ORDER BY ws.SCHNAME
"""

SQL_GET_APPROVED_PLANS = """
SELECT 
    dp.DID,
    dpt.DEPNAME,
    dp.SUMMARUB,
    dpd.SCHID,
    wsch.SCHNAME,
    dpd.SCOUNT,
    dpd.AMOUNTRUB,
    dp.PDATE,
    d.DNAME AS DOCTOR_NAME
FROM DAILYPLAN dp
LEFT JOIN DEPARTMENTS dpt ON dpt.DEPNUM = dp.DEPNUM
LEFT JOIN DAILYPLANDET dpd ON dpd.DID = dp.DID
LEFT JOIN WSCHEMA wsch ON wsch.SCHID = dpd.SCHID
JOIN DAILYPLANREF dpr ON dp.PLANTYPE = dpr.PLANTYPE
LEFT JOIN DOCTOR d ON d.DCODE = dp.DCODE
WHERE dp.PCODE = ?
  AND dp.PLANTYPE = 6296
ORDER BY dp.PDATE, dp.DID;
"""

SQL_PRIMARY_APPTS_TODAY = """
SELECT
    c.PCODE,
    c.LASTNAME,
    c.FIRSTNAME,
    c.MIDNAME,
    c.BDATE,
    d_cons.DNAME AS CONSULT_DOCTOR,
    f.FIRSTWORKDATE AS FirstWorkDate
FROM CLIENTS c
JOIN (
    SELECT
      r.PCODE,
      MIN(r.SCHEDULE_WORKDATE) AS FIRSTWORKDATE
    FROM REP_SCHED_APPEALS_VIEW r
    GROUP BY r.PCODE
) f
  ON f.PCODE = c.PCODE
LEFT JOIN DOCTOR d_cons
  ON d_cons.DCODE = c.DCODE_CONSULT
WHERE CAST(f.FIRSTWORKDATE AS DATE) = ?;
"""

SQL_GET_APPROVED_PLANS_PAID = """
SELECT CAST(COALESCE(SUM(p.BALANCEAMOUNT), 0) AS DOUBLE PRECISION) AS PAID_SUM
FROM PAYLOG p
WHERE p.PCODE = ?
"""

SQL_GET_TREATCODES = """
SELECT TREATCODE
FROM TREAT
WHERE PCODE = ?
ORDER BY TREATCODE
"""

SQL_GET_STAGE = """
SELECT pi.VALUETEXT
FROM PARAMSINFO pi
JOIN GROUPSPARAMS gp ON gp.CODEPARAMS = pi.CODEPARAMS
WHERE pi.TREATCODE = ?
  AND gp.NAMEPARAMS LIKE 'Следующий этап%'
"""

SQL_GET_FUTURE_APPOINTMENTS = """
SELECT 
    r.PCODE,
    r.SCHEDID,
    CAST(r.SCHEDULE_WORKDATE AS VARCHAR(10)) AS WORK_DATE_STR,
    d.DNAME AS DOCTOR_NAME,
    f.FULLNAME AS FILIAL_NAME,
    r.SCHEDAPPEALS_COMMENT
FROM REP_SCHED_APPEALS_VIEW r
LEFT JOIN DOCTOR d ON d.DCODE = r.DCODE
LEFT JOIN FILIALS f ON f.FILID = r.SCHEDFILIAL
WHERE r.PCODE = ?
  AND r.SCHEDULE_WORKDATE > CURRENT_DATE
ORDER BY r.SCHEDULE_WORKDATE
"""

SQL_GET_SCHEDULE_INFO = """
SELECT BHOUR, BMIN, FHOUR, FMIN
FROM SCHEDULE
WHERE SCHEDID = ?
"""


